name: github-actions
on:
  push:
    branches:
    - master
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the experiment
      run: |
        set -x
        sudo snap install --classic code
        code -v
        $WORKSPACE=$(node .)
        echo $WORKSPACE
        ls -a $WORKSPACE
        cat $WORKSPACE/index.log
