name: main
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run the experiment
      run: |
        set -x
        sudo snap install --classic code
        code -v
        node .
